services:
  ducks:
    build:
      context: .
      args: 
        ENV: ${ENV}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      - db
    environment:
      ENV: ${ENV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - ducks-network
    restart: no
    container_name: ducks
    ports:
      - 4242:4242
  db: 
    image: postgres
    container_name: ducks-db
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ducks
    volumes:
      - ducks-data:/var/lib/postgresql/data
    restart: no
    networks:
      - ducks-network

networks:
  ducks-network:
    driver: bridge
    
volumes:
  ducks-data:
    driver: local
